/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Conexion.MySql;
import com.sun.glass.events.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JOptionPane;

/**
 *
 * @author VOSTRO
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    private String usuarioID = "1";
    private String usuarioNombre = "admin";
    private String usuarioTipo = "admin";
    private MySql conector = null;
    private int[] combinar = {0,0,0,0};
    private String msjNoConectado =  "Usted no tiene permiso para entrar a esta zona";
    
    private boolean administrador = false,supervisor = false, cajero = false;
    
    public void msj(){
        JOptionPane.showMessageDialog(null,this.msjNoConectado,"Solo personal autorizado",JOptionPane.WARNING_MESSAGE);
    }
    
    public void validarTipoUsuario(){
        administrador = false; 
        supervisor = false;
        cajero = false;
        switch(this.usuarioTipo){
            case "administrador":
                this.administrador = true;
                break;
            case "supervisor":
                this.supervisor = true;
                break;
            case "cajero":
                this.cajero = true;
                break;
        }
    }

    public void setUsuarioTipo(String usuarioTipo) {
        this.usuarioTipo = usuarioTipo;
    }
    
    public void setUsuarioID(String usuarioID) {
        this.usuarioID = usuarioID;
    }

    public void setUsuarioNombre(String usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }

    public void setConector(MySql conector) {
        this.conector = conector;
    }
    
    
    public MainMenu(MySql conector,String usuarioID,String usuarioNombre,
            String usuarioTipo) {
        initComponents();
        this.setConector(conector);
        this.setUsuarioID(usuarioID);
        this.setUsuarioNombre(usuarioNombre);
        this.setUsuarioTipo(usuarioTipo);
        this.validarTipoUsuario();
        this.jLabelUsuarioConectado.setText(usuarioNombre);
        this.setLocationRelativeTo(null);
    }
    public void cliente(){
        if(this.administrador || this.cajero || this.supervisor){
            ClienteAdministrar cliente = new ClienteAdministrar(this.conector
                    ,this.usuarioID,this.usuarioNombre);
            cliente.setYo(cliente);
            cliente.setVisible(true);
        }else{
            this.msj();
        }
    }
    
    public void Proveedor(){
        if(this.administrador || this.supervisor){
            ProveedorAdministrar proveedor = new ProveedorAdministrar(this.conector
                    ,this.usuarioID,this.usuarioNombre);
            proveedor.setYo(proveedor);
            proveedor.setVisible(true);
        }else{
            this.msj();
        }
    }
    
    public void Producto(){
        if(this.administrador || this.supervisor){
            ProductoAdministrar producto = new ProductoAdministrar(this.conector,
                    this.usuarioID,this.usuarioNombre);
            producto.setVisible(true);
        }else{
            this.msj();
        }
    }
    
    public void ComprarProducto(){
        if(this.administrador || this.supervisor){
            CompraProductoAdministrar compra = new CompraProductoAdministrar(this.conector,
                    this.usuarioID,this.usuarioNombre);
            compra.setYo(compra);
            compra.setVisible(true);
        }else{
            this.msj();
        }
    }
    
    public void usuario(){
        if(this.administrador){
        
            UsuariosAdministrar usuario = new UsuariosAdministrar(this.conector,
                    this.usuarioID,this.usuarioNombre);
            usuario.setVisible(true);
        }else{
            this.msj();
        }
    }
    public void acercade(){
        if(this.administrador || this.cajero || this.supervisor){
            AcercaDe acercaDe = new AcercaDe();
            acercaDe.setVisible(true);
        }else{
            this.msj();
        }
    }
    public void TipoTelefono(){
        //TipoTelefonoAdministrar
        if(this.administrador || this.cajero || this.supervisor){
            TipoTelefonoAdministrar tipoTelefono = new TipoTelefonoAdministrar(this.conector,
                    this.usuarioID,this.usuarioNombre);
            tipoTelefono.setVisible(true);
        }else{
            this.msj();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelUsuarioConectado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuAdministrar = new javax.swing.JMenu();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuItemTipoTelefono = new javax.swing.JMenuItem();
        jMenuItemProveedor = new javax.swing.JMenuItem();
        jMenuItemProducto = new javax.swing.JMenuItem();
        jMenuItemProducto1 = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("Usuario conectado");

        jLabelUsuarioConectado.setText("jLabel1");

        jMenuInicio.setText("Inicio");

        jMenuItem1.setText("Salir");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenuInicio.add(jMenuItem1);

        jMenuBar1.add(jMenuInicio);

        jMenuAdministrar.setText("Administración");

        jMenuItemUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemUsuario.setText("Usuario");
        jMenuItemUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemUsuarioMousePressed(evt);
            }
        });
        jMenuAdministrar.add(jMenuItemUsuario);

        jMenuItemCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemClienteMousePressed(evt);
            }
        });
        jMenuAdministrar.add(jMenuItemCliente);

        jMenuItemTipoTelefono.setText("Tipo Teléfono");
        jMenuItemTipoTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemTipoTelefonoMousePressed(evt);
            }
        });
        jMenuAdministrar.add(jMenuItemTipoTelefono);

        jMenuItemProveedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemProveedor.setText("Proveedor");
        jMenuItemProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemProveedorMousePressed(evt);
            }
        });
        jMenuAdministrar.add(jMenuItemProveedor);

        jMenuItemProducto.setText("Producto");
        jMenuItemProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemProductoMousePressed(evt);
            }
        });
        jMenuAdministrar.add(jMenuItemProducto);

        jMenuItemProducto1.setText("Comprar Producto");
        jMenuItemProducto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemProducto1MousePressed(evt);
            }
        });
        jMenuAdministrar.add(jMenuItemProducto1);

        jMenuBar1.add(jMenuAdministrar);

        jMenuAyuda.setText("Ayuda");

        jMenuItemAcercaDe.setText("Acerca de");
        jMenuItemAcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemAcercaDeMousePressed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcercaDe);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUsuarioConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelUsuarioConectado))
                .addGap(0, 265, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAcercaDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeMousePressed
        // TODO add your handling code here:

          this.acercade();
    }//GEN-LAST:event_jMenuItemAcercaDeMousePressed

    private void jMenuItemUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioMousePressed
        // TODO add your handling code here:
         this.usuario();        
    }//GEN-LAST:event_jMenuItemUsuarioMousePressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        //System.out.println(evt.getKeyChar());
        System.out.println(evt.getKeyCode());
        if( evt.getKeyCode() == KeyEvent.VK_CONTROL){
            this.combinar[0] = KeyEvent.VK_CONTROL; 

        }else if(evt.getKeyCode() == KeyEvent.VK_SHIFT){
        }else if(evt.getKeyCode() == KeyEvent.VK_U ){
            this.combinar[1] = KeyEvent.VK_U;
            if((this.combinar[0] == 17) && (this.combinar[1] == 85)){
                this.usuario();        
            }
        }else if(evt.getKeyCode() == KeyEvent.VK_C ){
            this.combinar[1] = KeyEvent.VK_C;
            if((this.combinar[0] == KeyEvent.VK_CONTROL) &&
                    (this.combinar[1] == KeyEvent.VK_C)){
                this.cliente();        
            }
        }else if(evt.getKeyCode() == KeyEvent.VK_P ){
            this.combinar[1] = KeyEvent.VK_P;
            if((this.combinar[0] == KeyEvent.VK_CONTROL) &&
                    (this.combinar[1] == KeyEvent.VK_P)){
                this.Proveedor();        
            }
        }else{
            System.out.println("4 "+evt.getKeyCode());
            this.combinar[0] = 0;
            this.combinar[1] = 0;
        } 
    }//GEN-LAST:event_formKeyPressed

    private void jMenuItemClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemClienteMousePressed
        // TODO add your handling code here:
        this.cliente();
    }//GEN-LAST:event_jMenuItemClienteMousePressed

    private void jMenuItemTipoTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemTipoTelefonoMousePressed
        // TODO add your handling code here:
        this.TipoTelefono();
    }//GEN-LAST:event_jMenuItemTipoTelefonoMousePressed

    private void jMenuItemProveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemProveedorMousePressed
        // TODO add your handling code here:
        
        this.Proveedor();
    }//GEN-LAST:event_jMenuItemProveedorMousePressed

    private void jMenuItemProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemProductoMousePressed
        // TODO add your handling code here:
        this.Producto();
    }//GEN-LAST:event_jMenuItemProductoMousePressed

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1MousePressed

    private void jMenuItemProducto1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemProducto1MousePressed
        // TODO add your handling code here:
        this.ComprarProducto();
    }//GEN-LAST:event_jMenuItemProducto1MousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelUsuarioConectado;
    private javax.swing.JMenu jMenuAdministrar;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemProducto;
    private javax.swing.JMenuItem jMenuItemProducto1;
    private javax.swing.JMenuItem jMenuItemProveedor;
    private javax.swing.JMenuItem jMenuItemTipoTelefono;
    private javax.swing.JMenuItem jMenuItemUsuario;
    // End of variables declaration//GEN-END:variables

}
